name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show Hello
        run: echo "Hello World"
      - name: Say Goodbye
        run: echo "Goodbye! Everithing is ok!"
